#ifndef PRIMES_LABS_LAB_2_PRIMES_MILLER_RABIN_TEST_H_
#define PRIMES_LABS_LAB_2_PRIMES_MILLER_RABIN_TEST_H_

bool MillerTest(unsigned long d, unsigned long n);

#endif //PRIMES_LABS_LAB_2_PRIMES_MILLER_RABIN_TEST_H_
